In [1]:
import numpy as np

In [2]:
# create array
arr1=np.array([1,2,3,4])

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.ndim

1

In [7]:
arr1=np.array(([1,2,3,4],[5,6,7,8]))


In [8]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.ndim

2

In [11]:
# shape & size
arr1.shape

(2, 4)

In [16]:
arr1.size

8

In [21]:
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [22]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
arr3.ndim

3

In [27]:
arr3.shape

(1, 3, 3)

In [29]:
# wap to slice data 5 from arr3.

In [37]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr3[0][1]

array([4, 5, 6])

In [39]:
arr3[0][1][1]

5

In [41]:
# max, min
arr3.max()

9

In [42]:
arr3.min()

1