In [1]:
# wap to calculate the sum of 3 by 2 matrix w.r.t to column wise and row wise.

In [2]:
import numpy as np

In [11]:
x =np.array([[1,2],[4,5],[7,8]])

In [12]:
x

array([[1, 2],
       [4, 5],
       [7, 8]])

In [13]:
x.sum(axis=0)

array([12, 15])

In [14]:
x.sum(axis=1)

array([ 3,  9, 15])

In [15]:
# arg max
# arg min 
# arg sort 
# sort
x


array([[1, 2],
       [4, 5],
       [7, 8]])

In [28]:
arr=np.array([[[23,78,4],[94,4,21],[78,56,43]]])

In [29]:
arr

array([[[23, 78,  4],
        [94,  4, 21],
        [78, 56, 43]]])

In [20]:
# sort
arr.sort()

In [21]:
arr

array([[[ 4, 23, 78],
        [ 4, 21, 94],
        [43, 56, 78]]])

In [22]:
arr.min()

4

In [24]:
arr.max()

94

In [30]:
# arg-------------> sort,min,max #--------------- it depend on indexing.
arr

array([[[23, 78,  4],
        [94,  4, 21],
        [78, 56, 43]]])

In [33]:
arr.argsort()  #---------indexing ko sort kar rha h !!!!!!

array([[[2, 0, 1],
        [1, 2, 0],
        [2, 1, 0]]], dtype=int64)

In [34]:
arr.argmax()

3

In [35]:
arr.argmin()

2