In [1]:
# wap to find common element in a list.

In [4]:
a=[1,2,3,4]
b=[4,5,6,2]
def common(a,b):
    for i in a:
        for j in b:
            if i==j:
                print(i)
        else:
                print('-1')
    

In [5]:
common(a,b)

-1
2
-1
-1
4
-1


In [6]:
# wap to make a array 2 by 3.

In [7]:
import numpy as np

In [8]:
x=np.array([[1,2,3],[67,89,-5]])
    

In [9]:
x

array([[ 1,  2,  3],
       [67, 89, -5]])

In [10]:
x.shape

(2, 3)

In [11]:
x.size

6

In [12]:
x = np.array([1,2,'python'])

In [13]:
x

array(['1', '2', 'python'], dtype='<U11')

In [14]:
type(x)

numpy.ndarray

In [15]:
x.shape

(3,)

In [16]:
x.size

3

In [20]:
# ones & zeroes
np.zeros(0)


array([], dtype=float64)

In [21]:
np.zeros(1)

array([0.])

In [24]:
np.zeros([10,20])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [ ]:
# wap to make a 3d matrix of 0.

In [55]:
z=np.zeros([5,3,3])

In [56]:
z.shape

(5, 3, 3)

In [57]:
z.size

45

In [58]:
z.ndim

3

In [59]:
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [62]:
y=np.ones(0)

In [63]:
y

array([], dtype=float64)

In [67]:
y=np.ones([5,2])

In [68]:
y

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# wap to make a data of ones 5 by 6 with the help of tuple.

In [69]:
y=np.ones([5,6])

In [70]:
y

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [71]:
y.shape

(5, 6)

In [72]:
y.size

30

In [73]:
y.ndim

2

In [85]:
# arange
np.arange(100,2,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3])

In [96]:
# empty function
np.empty(51)

array([1.34954198e-311, 1.34951954e-311, 1.34951943e-311, 1.34955399e-311,
       1.34951943e-311, 1.34955407e-311, 1.34955406e-311, 1.34951943e-311,
       1.34951943e-311, 1.34955406e-311, 1.34955407e-311, 1.34955407e-311,
       1.34951943e-311, 1.34955407e-311, 1.34955407e-311, 1.34955406e-311,
       1.34951943e-311, 1.34955406e-311, 1.34955407e-311, 1.34955284e-311,
       1.34955399e-311, 1.34954251e-311, 1.34955406e-311, 1.34955401e-311,
       1.34951943e-311, 1.34951943e-311, 1.34955406e-311, 1.34955406e-311,
       1.34951943e-311, 1.34955245e-311, 1.34955409e-311, 1.34951943e-311,
       1.34951943e-311, 1.34951943e-311, 1.34951943e-311, 1.34951943e-311,
       1.34955245e-311, 1.34955245e-311, 1.34951943e-311, 1.34955245e-311,
       1.34951943e-311, 1.34955245e-311, 1.34951943e-311, 1.34951943e-311,
       1.34955245e-311, 1.34955245e-311, 1.34955432e-311, 1.34955432e-311,
       1.34951943e-311, 1.34955407e-311, 1.34951943e-311])

In [101]:
np.empty([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [117]:
# identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [1]:
# transpose matrix
# wap to create a matrix 3 by 3.


In [26]:
import numpy as np
a =np.array([[1,2,3],[4,5,6],[6,7,8]])

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [28]:
a.shape

(3, 3)

In [29]:
a.T

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 8]])

In [39]:
# linspace
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [40]:
#axis = 0 
#axis = 1
a

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [41]:
a.sum()

42

In [43]:
a.sum(axis=0) #-----column by add

array([11, 14, 17])

In [46]:
a.sum(axis=1)  #------row by add

array([ 6, 15, 21])